#+OPTIONS: html-style:nil toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css"/>
#+TITLE: Philipp Heumann

I am an epidemiologist and PhD student in the Division of Cancer Epidemiology at the German Cancer Research Center.

My research is focused on patient-reported toxicities in cancer patients treated with radiotherapy.

Here you can find my [[./cv.pdf][CV]].

* Publications
** 2025
@@html:<div class="pub"><mark>@@Heumann P@@html:</mark>@@, Benner A, Behrens S, Chang-Claude J, Seibold P. /Prognostic value of cancer-related fatigue at the end of radiotherapy for overall survival ≥ 10 years in women with breast cancer/. Breast Cancer Res. [[https://breast-cancer-research.biomedcentral.com/articles/10.1186/s13058-025-02036-3][doi:10.1186/s13058-025-02036-3]]. @@html:</div>@@

@@html:<div class="pub">@@Aguado-Barrera ME, Lopez-Pleguezuelos C, Gómez-Caamaño A, Calvo-Crespo P, Taboada-Valladares B, Azria D, Boisselier P, Briers E, Chan C, Chang-Claude J, Coedo-Costa C, Crujeiras-González A, Cuaron JJ, Defraene G, Elliott RM, Faivre-Finn C, Franceschini M, Fuentes-Rios O, Galego-Carro J, Gutiérrez-Enríquez S, @@html:<mark>@@ Heumann P @@html:</mark>@@, Higginson DS, Johnson K, Lambrecht M, Lang P, Lievens Y, Mollà M, Ramos M, Rancati T, Rattay T, Rimner A, Rosenstein BS, Sangalli C, Seibold P, Sperk E, Stobart H, Symonds P, Talbot CJ, Vandecasteele K, Veldeman L, Ward T, Webb A, Woolf D, de Ruysscher D, West CML, Vega A; REQUITE Consortium. /Professional-patient discrepancies in assessing lung cancer radiotherapy symptoms: An international multicentre study/. Lung Cancer. [[https://www.lungcancerjournal.info/article/S0169-5002(24)00606-8/fulltext][doi:10.1016/j.lungcan.2024.108072]]. @@html:</div>@@

** 2023
@@html:<div class="pub"><mark>@@Heumann P@@html:</mark>@@, Aguado-Barrera ME, Avuzzi B, Azria D, Briers E, Bultijnck R, Choudhury A, De Ruysscher D, Farcy-Jacquet MP, Fonteyne V, Gómez Caamaño A, Helmbold I, Johnson K, Kerns SL, Lambrecht M, Lingard Z, Rancati T, Rosenstein BS, Sperk E, Paul Symonds R, Talbot C, Valdagni R, Vega A, Veldeman L, Ward T, Webb A, West CM, Chang-Claude J, Seibold P; REQUITE Consortium. /Comparing symptom reporting by prostate cancer patients and healthcare professionals in the international multicentre REQUITE study/. Radiother Oncol. [[https://www.thegreenjournal.com/article/S0167-8140(22)04563-7/fulltext][doi:10.1016/j.radonc.2022.11.015]]. @@html:</div>@@
