#+OPTIONS: html-style:nil toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css"/>
#+TITLE: Philipp Heumann

I am an epidemiologist and associate researcher in the Department of Urology at the Sahlgrenska Academy, University of Gothenburg, Sweden.

My research is currently focused on the early detection of prostate cancer.

Here you can find my [[./cv.pdf][CV]].

* Selected Publications
** 2026
@@html:<div class="pub"><mark>@@Heumann P*@@html:</mark>@@, Aguado-Barrera ME*, Jandu HK, Azria D, Briers E, Bultijnck R, Chang-Claude J, Choudhury A, Dunning AM, Fachal L, Fuentes-Ríos O, Gómez-Caamaño A, Gutiérrez-Enríquez S, Kaaks R, Kerns SL, Lambrecht M, Romero JCR, Rosenstein BS, De Ruysscher D, Schmidt ME, Sperk E, Stobart H, Symonds RP, Veldeman L, Veldwijk MR, Ward T, Webb A, West CML, Rancati T, Rattay T, Vega A; REQUITE Consortium; Talbot CJ, Seibold P. /Genetic determinants of fatigue up to 2 years after radiotherapy in prostate cancer patients/. Nat Commun. [[https://www.nature.com/articles/s41467-026-72041-3][doi:10.1038/s41467-026-72041-3]] @@html:</div>@@

** 2025
@@html:<div class="pub"><mark>@@Heumann P@@html:</mark>@@, Benner A, Behrens S, Chang-Claude J, Seibold P. /Prognostic value of cancer-related fatigue at the end of radiotherapy for overall survival ≥ 10 years in women with breast cancer/. Breast Cancer Res. [[https://breast-cancer-research.biomedcentral.com/articles/10.1186/s13058-025-02036-3][doi:10.1186/s13058-025-02036-3]]. @@html:</div>@@

@@html:<div class="pub">@@Aguado-Barrera ME, Lopez-Pleguezuelos C, Gómez-Caamaño A, Calvo-Crespo P, Taboada-Valladares B, Azria D, Boisselier P, Briers E, Chan C, Chang-Claude J, Coedo-Costa C, Crujeiras-González A, Cuaron JJ, Defraene G, Elliott RM, Faivre-Finn C, Franceschini M, Fuentes-Rios O, Galego-Carro J, Gutiérrez-Enríquez S, @@html:<mark>@@ Heumann P @@html:</mark>@@, Higginson DS, Johnson K, Lambrecht M, Lang P, Lievens Y, Mollà M, Ramos M, Rancati T, Rattay T, Rimner A, Rosenstein BS, Sangalli C, Seibold P, Sperk E, Stobart H, Symonds P, Talbot CJ, Vandecasteele K, Veldeman L, Ward T, Webb A, Woolf D, de Ruysscher D, West CML, Vega A; REQUITE Consortium. /Professional-patient discrepancies in assessing lung cancer radiotherapy symptoms: An international multicentre study/. Lung Cancer. [[https://www.lungcancerjournal.info/article/S0169-5002(24)00606-8/fulltext][doi:10.1016/j.lungcan.2024.108072]]. @@html:</div>@@

** 2023
@@html:<div class="pub"><mark>@@Heumann P@@html:</mark>@@, Aguado-Barrera ME, Avuzzi B, Azria D, Briers E, Bultijnck R, Choudhury A, De Ruysscher D, Farcy-Jacquet MP, Fonteyne V, Gómez Caamaño A, Helmbold I, Johnson K, Kerns SL, Lambrecht M, Lingard Z, Rancati T, Rosenstein BS, Sperk E, Paul Symonds R, Talbot C, Valdagni R, Vega A, Veldeman L, Ward T, Webb A, West CM, Chang-Claude J, Seibold P; REQUITE Consortium. /Comparing symptom reporting by prostate cancer patients and healthcare professionals in the international multicentre REQUITE study/. Radiother Oncol. [[https://www.thegreenjournal.com/article/S0167-8140(22)04563-7/fulltext][doi:10.1016/j.radonc.2022.11.015]]. @@html:</div>@@
